### ISSUE TITLE
Default markup structure includes `header` and `h1`

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-cookie-message#101]
The default markup structure includes a `header` with nested `h1` elements into the overall page markup. 

## What

When the default cookie message is inserted into the page, it inserts `header` and `h1` tags into the page. This has been reported as an issue during accessibility review.

While we can override the default markup and insert our own, we would lose the benefit of using automatically generated copy and it would be necessary to check it whenever the underlying component is updated. 

Suggestion - provide a simpler cookie message or a way to provide custom HTML with a placeholder for the default copy.

**Comment by notlee** [comment]
hey @petrklus, thanks for flagging along with the other issues, we'll replace the default heading with a `h2`

**Comment by notlee** [comment]
Oh and I've removed the use of `header`!
