### ISSUE TITLE
Remove unused options

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-cookie-message#126]
Remove the following unused JS options:
- `acceptUrl`
- `acceptUrlFallback`
- `manageCookiesUrl`
- `consentCookieName`

They appear not to be used. In addition, we do not document them, which could lead to a poor experience if attempted without guidance. For example setting only `consentCookieName` of the above options would lead to a cookie message which could not be dismissed or permanently accepted without significant custom code.

**Comment by notlee** [comment]
This issue came up whilst working on adding tracking to the registry: https://github.com/Financial-Times/origami-registry-ui/pull/413

**Comment by chee** [comment]
if we never documented these options, is it really a breaking change?

**Comment by chee** [comment]
Do you mean that nobody ever configures these settings in an app?

**Comment by notlee** [comment]
Yeah, not that I have access to / can find at least

**Comment by JakeChampion** [comment]
The only place in the Financial-Times GitHub organisation which uses any of these options is https://github.com/Financial-Times/o-cookie-message/blob/master/test/oCookieMessage.test.js#L39
