### ISSUE TITLE
Handle Safari private browsing exceptions

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-cookie-message#20]
I get the following exceptions from Safari users:
- `SecurityError: DOM Exception 18`
- `QuotaExceededError: DOM Exception 22`

apparently it's related to Safari private browsing.

I have Sentry errors if needed.

**Comment by JakeChampion** [comment]
Thanks for creating this issue, localstorage doesn't work for private browsing users. We will probably have to use https://github.com/matthew-andrews/superstore-sync to work around this edge case.

**Comment by alicebartlett** [comment]
#26

**Comment by alicebartlett** [comment]
Fix this @kavanagh! Sorry that took so long.
Still working on #21...

**Comment by kavanagh** [comment]
🙇 Thank you!
