### ISSUE TITLE
Handle localStorage SecurityError on ChromeMobile 

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-cookie-message#21]
I have reports of users getting the following exception on Chrome Mobile / Android:

```
SecurityError
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

Apparently happens when users block third-party cookies and data.

I have Sentry errors I can assign if needed.

I'm using the build service to load this module. Does this mean the data becomes "third-party"?

Probably related to #20

**Comment by alicebartlett** [comment]
I'm able to replicate this by:
1. blocking cookies: https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DAndroid&hl=en

Unfortunately superstore-sync does not fix this error for us, but since I'm able to replicate this it should be fine. I do not think this is a build service issue.

**Comment by alicebartlett** [comment]
https://github.com/matthew-andrews/superstore-sync/pull/11

Added a PR to supserstore-sync to fix this
