### ISSUE TITLE
a few design tweaks

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-cookie-message#48]
To add capitals to Cookie Policy and Cookie Settings (approved with Legal) 

To cap the max line length at desktop to make it easier to read. 

Lastly to fix the 'x' close icon position at mobile and tweak text padding/margins. 

![v 2 cookie message 2x](https://user-images.githubusercontent.com/11214093/32784439-c46d7a5a-c946-11e7-9914-a013956d09f7.png)

![v 2 cookie message mobile 2x](https://user-images.githubusercontent.com/11214093/32784429-bda173fc-c946-11e7-878a-200592cedeeb.png)

**Comment by JakeChampion** [comment]
@draysonandstock Thanks for the issue, what line length should it be capped at?

**Comment by draysonandstock** [comment]
Hi Jake, I had it running over 8 columns. So about 135 characters if possible. 

Cheers,
