### ISSUE TITLE
To update o-cookie-message. 

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-cookie-message#57]
In order to be compliant and to allow specialist titles to also use the updated cookie banner we need to update this component. 

**Sketch file is here:**
https://drive.google.com/file/d/0B8f0KVx7ey79VHpUNzAtdkVlc1E/view

Our (GDPR) Trello ticket for this is here: https://trello.com/c/WWlo1pZw/327-white-label-cookie-banner

*Main things to consider:*
- Will update you with the required functionality but in short this component should have that and styling. 
- This design will be the same for both FT.com and Specialist titles as we can't do a true white label version without first looking at o-typography. 
- The link style uses that of the Neutral Alert Message. 

Any questions let me know. 

![screen shot 2018-06-05 at 15 02 43](https://user-images.githubusercontent.com/11214093/40981859-ee21b2f8-68d3-11e8-9242-44b23a899cbf.png)

**Notes on implementation**
The Accept button should sit within a form element and submit it. The form action should be of the form:
```
<form method="get" action="https://consent.<DOMAIN>/__consent/consent-record-cookie">
```

Where <DOMAIN> is the site eg exec-appointments.com, fdimarkets.com

The form should also contain a hidden input:
```
<input type="hidden" name="redirect" value="<URL TO REDIRECT TO E.G CURRENT PAGE>"	/>
```
This will set the cookie and reload the page. As an enhancement you could do an async request and hide the banner on success but you'd need to write the code for that.

**Comment by gvonkoss** [comment]
#58
