### ISSUE TITLE
Privacy Policy Message

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-cookie-message#65]
According to the attached document, the cookie message needs to appear along side a privacy policy message for some FT websites.

<img width="231" alt="screen shot 2018-07-17 at 12 12 38" src="https://user-images.githubusercontent.com/16777943/42814007-b94d16a0-89ba-11e8-82b7-1330a0e1c75b.png">

This is a temporary addition to cookie message, and can be removed by end of September

Reference:
[Wavteq cookie banner requirements.pdf](https://github.com/Financial-Times/o-cookie-message/files/2201357/Wavteq.cookie.banner.requirements.pdf)

**Comment by ryanolee** [comment]
Hi @gvonkoss,
Are there any updates on reverting these changes? As they are no longer required.
Thanks!

**Comment by gvonkoss** [comment]
Hi @ryanolee I've been waiting for that request to come through formally, I'd be happy to revert them if we could get confirmation in writing to origami.support@ft.com

**Comment by rowanmanning** [comment]
We should just remove this, possibly just as part of the next breaking change #82

**Comment by chee** [comment]
i'm going to remove this as part of #82
