### ISSUE TITLE
brand o-cookie-message

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-cookie-message#93]
o-cookie-message v4 is used, unbranded, by whitelabel users such as FDI Intelligence.
o-cookie-message v5 introduced a new version of o-colors which removed ft.com specific 
colours from the colour palette. As o-cookie-message is not branded Sass builds may now 
fail, for example if the "alternative" style is included which uses `jade`.

So witelabel users may safety upgrade add official whitelabel brand support to o-cookie-message.

**Comment by chee** [comment]
@notlee has anything changed around this, now that cookie message no longer depends on `o-banner`? I'm not 100% clear on what we need to do to close this

**Comment by notlee** [comment]
Hmm. I think we probably do want to brand o-cookie-message for specialist titles but no one is asking for it. I'd be happy to close this issue until someone requests o-cookie-message brand customisation, with a note of "something something design tokens"
