### ISSUE TITLE
Add a new Accept All / Reject All variant

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-cookie-message#96]
I've been speaking to @tsib0 who is currently working on cookie consent in Specialist Titles and FT Live. Ideally these projects will be able to use the same cookie management as FT.com, but if they can't then a new shared way to manage cookies will need to be built for these products.

If a new way of setting cookies is being built, then they would like to do the smallest amount of work possible to be compliant, the proposed solution is to have a cookie banner with no "manage cookies" link, and two buttons: Accept All, and Reject All.

We'd need to do some work to this component if we'd like to support this. We shouldn't do anything until @tsib0 confirms that this will be the approach, but opening this issue so we have somewhere to track it.

**Comment by tsib0** [comment]
For all the Specialist titles this concerns we took the option of moving all the microsites to main domains and adding o-cookie-message as normal, so this new variant won't be required now.

**Comment by rowanmanning** [comment]
Great! Thanks for keeping us in the loop :)
